### PR TITLE
Allow specifying alt path to config file

### PR DESCRIPTION
**Pull request by tejr**
For the simplest way to get this working, add the expected `--config` or `-c` option, and arrange for it to modify the value of `Funtoo::Report`'s `$config_update` variable if specified, by changing it to a package variable (`our` vs `my`). Update documentation to match.

This is not an ideal implementation, but it's the simplest route to getting what we need. Ideally what we should do is create instances of the `Funtoo::Report` module with some very basic OOP, so that two modules can exist in parallel with different configuration files. Such a change requires consultation with the other developers.

For the moment, however, I just wanted something that would make automated tests more straightforward to implement, and this should accomplish that.

This implements the feature wanted for GitHub issue #82.

### CODE REVIEW

**Comment by palica** [comment]
why are 
```
funtoo-report -u -c /etc/funtoo-report-2.conf
...
Creating or replacing /etc/funtoo-report.conf
```
and
```
funtoo-report -c /etc/funtoo-report-2.conf -u
...
Creating or replacing /etc/funtoo-report-2.conf
```
treated differently?

Only the second works as expected. Bug?

**Comment by tejr** [comment]
Yeah, that'll be the order of options mattering (which it shouldn't). Just have to change the order of execution a bit. I'll review that this evening unless @ShadowM00n beats me to it.

**Comment by tejr** [comment]
> <ShadowM00n> if you're not too invested, I'll take care of the config-related things
> <ShadowM00n> the alt-config and the logic/combination thing
> <tejr> go for it, i was going to do it this evening if you didn't get to it first, as i suspected you might be interested
> <tejr> all i was going to do was delay the executing of the actual action until all the options had been parsed
> <tejr> there may be a Smarter way
> <tejr> once it works it's a big win for testability, which i'm looking forward to

**Comment by ShadowM00n** [comment]
I made a commit that should handle order of operations/weight and also threw in the ability to view the (implicitly or explicitly) selected config.

**Pull request merged**
